server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.56.101
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
leyou:
  jwt:
    pubKeyPath: /Users/mingmingya/IDEA_leyou/rsa/rsa.pub # 公钥地址
    cookieName: ly_token